import = ["/home/noodlebowl/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = true

[env]
TERM = "alacritty"

[font]
size = 11.0

[font.normal]
family = "Source Code Pro"
style = "Regular"

[window]
dynamic_padding = false
opacity = 0.85

[window.padding]
x = 18
y = 16
